/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing AddGroupToCollectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddGroupToCollectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddGroupToCollectionRequest
        //private AddGroupToCollectionRequest instance;

        public AddGroupToCollectionRequestTests()
        {
            // TODO uncomment below to create an instance of AddGroupToCollectionRequest
            //instance = new AddGroupToCollectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddGroupToCollectionRequest
        /// </summary>
        [Fact]
        public void AddGroupToCollectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddGroupToCollectionRequest
            //Assert.IsInstanceOfType<AddGroupToCollectionRequest> (instance, "variable 'instance' is a AddGroupToCollectionRequest");
        }


        /// <summary>
        /// Test the property 'GroupKey'
        /// </summary>
        [Fact]
        public void GroupKeyTest()
        {
            // TODO unit test for the property 'GroupKey'
        }
        /// <summary>
        /// Test the property 'AccessLevel'
        /// </summary>
        [Fact]
        public void AccessLevelTest()
        {
            // TODO unit test for the property 'AccessLevel'
        }

    }

}
