/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing AddUserToCollectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddUserToCollectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddUserToCollectionRequest
        //private AddUserToCollectionRequest instance;

        public AddUserToCollectionRequestTests()
        {
            // TODO uncomment below to create an instance of AddUserToCollectionRequest
            //instance = new AddUserToCollectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddUserToCollectionRequest
        /// </summary>
        [Fact]
        public void AddUserToCollectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddUserToCollectionRequest
            //Assert.IsInstanceOfType<AddUserToCollectionRequest> (instance, "variable 'instance' is a AddUserToCollectionRequest");
        }


        /// <summary>
        /// Test the property 'UserKey'
        /// </summary>
        [Fact]
        public void UserKeyTest()
        {
            // TODO unit test for the property 'UserKey'
        }
        /// <summary>
        /// Test the property 'AccessLevel'
        /// </summary>
        [Fact]
        public void AccessLevelTest()
        {
            // TODO unit test for the property 'AccessLevel'
        }

    }

}
