/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing AddVersionToFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddVersionToFileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddVersionToFileRequest
        //private AddVersionToFileRequest instance;

        public AddVersionToFileRequestTests()
        {
            // TODO uncomment below to create an instance of AddVersionToFileRequest
            //instance = new AddVersionToFileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddVersionToFileRequest
        /// </summary>
        [Fact]
        public void AddVersionToFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddVersionToFileRequest
            //Assert.IsInstanceOfType<AddVersionToFileRequest> (instance, "variable 'instance' is a AddVersionToFileRequest");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'StorageService'
        /// </summary>
        [Fact]
        public void StorageServiceTest()
        {
            // TODO unit test for the property 'StorageService'
        }

    }

}
