/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing AttachToExistingFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttachToExistingFileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttachToExistingFileRequest
        //private AttachToExistingFileRequest instance;

        public AttachToExistingFileRequestTests()
        {
            // TODO uncomment below to create an instance of AttachToExistingFileRequest
            //instance = new AttachToExistingFileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttachToExistingFileRequest
        /// </summary>
        [Fact]
        public void AttachToExistingFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AttachToExistingFileRequest
            //Assert.IsInstanceOfType<AttachToExistingFileRequest> (instance, "variable 'instance' is a AttachToExistingFileRequest");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'StorageService'
        /// </summary>
        [Fact]
        public void StorageServiceTest()
        {
            // TODO unit test for the property 'StorageService'
        }
        /// <summary>
        /// Test the property 'StorageId'
        /// </summary>
        [Fact]
        public void StorageIdTest()
        {
            // TODO unit test for the property 'StorageId'
        }

    }

}
