/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing Collection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Collection
        //private Collection instance;

        public CollectionTests()
        {
            // TODO uncomment below to create an instance of Collection
            //instance = new Collection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Collection
        /// </summary>
        [Fact]
        public void CollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Collection
            //Assert.IsInstanceOfType<Collection> (instance, "variable 'instance' is a Collection");
        }



    }

}
