/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing CollectionItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectionItems
        //private CollectionItems instance;

        public CollectionItemsTests()
        {
            // TODO uncomment below to create an instance of CollectionItems
            //instance = new CollectionItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionItems
        /// </summary>
        [Fact]
        public void CollectionItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CollectionItems
            //Assert.IsInstanceOfType<CollectionItems> (instance, "variable 'instance' is a CollectionItems");
        }


        /// <summary>
        /// Test the property 'ChildCollections'
        /// </summary>
        [Fact]
        public void ChildCollectionsTest()
        {
            // TODO unit test for the property 'ChildCollections'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

    }

}
