/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing CopyFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CopyFileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CopyFileRequest
        //private CopyFileRequest instance;

        public CopyFileRequestTests()
        {
            // TODO uncomment below to create an instance of CopyFileRequest
            //instance = new CopyFileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CopyFileRequest
        /// </summary>
        [Fact]
        public void CopyFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CopyFileRequest
            //Assert.IsInstanceOfType<CopyFileRequest> (instance, "variable 'instance' is a CopyFileRequest");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'StorageService'
        /// </summary>
        [Fact]
        public void StorageServiceTest()
        {
            // TODO unit test for the property 'StorageService'
        }

    }

}
