/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing CreateFileRequestAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateFileRequestAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateFileRequestAllOf
        //private CreateFileRequestAllOf instance;

        public CreateFileRequestAllOfTests()
        {
            // TODO uncomment below to create an instance of CreateFileRequestAllOf
            //instance = new CreateFileRequestAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateFileRequestAllOf
        /// </summary>
        [Fact]
        public void CreateFileRequestAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateFileRequestAllOf
            //Assert.IsInstanceOfType<CreateFileRequestAllOf> (instance, "variable 'instance' is a CreateFileRequestAllOf");
        }


        /// <summary>
        /// Test the property 'StorageService'
        /// </summary>
        [Fact]
        public void StorageServiceTest()
        {
            // TODO unit test for the property 'StorageService'
        }

    }

}
