/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing CreateFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateFileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateFileRequest
        //private CreateFileRequest instance;

        public CreateFileRequestTests()
        {
            // TODO uncomment below to create an instance of CreateFileRequest
            //instance = new CreateFileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateFileRequest
        /// </summary>
        [Fact]
        public void CreateFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateFileRequest
            //Assert.IsInstanceOfType<CreateFileRequest> (instance, "variable 'instance' is a CreateFileRequest");
        }


        /// <summary>
        /// Test the property 'StorageService'
        /// </summary>
        [Fact]
        public void StorageServiceTest()
        {
            // TODO unit test for the property 'StorageService'
        }

    }

}
