/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing CreateRetentionPolicyRequestAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateRetentionPolicyRequestAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateRetentionPolicyRequestAllOf
        //private CreateRetentionPolicyRequestAllOf instance;

        public CreateRetentionPolicyRequestAllOfTests()
        {
            // TODO uncomment below to create an instance of CreateRetentionPolicyRequestAllOf
            //instance = new CreateRetentionPolicyRequestAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateRetentionPolicyRequestAllOf
        /// </summary>
        [Fact]
        public void CreateRetentionPolicyRequestAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateRetentionPolicyRequestAllOf
            //Assert.IsInstanceOfType<CreateRetentionPolicyRequestAllOf> (instance, "variable 'instance' is a CreateRetentionPolicyRequestAllOf");
        }


        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }

    }

}
