/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing CreateRetentionPolicyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateRetentionPolicyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateRetentionPolicyRequest
        //private CreateRetentionPolicyRequest instance;

        public CreateRetentionPolicyRequestTests()
        {
            // TODO uncomment below to create an instance of CreateRetentionPolicyRequest
            //instance = new CreateRetentionPolicyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateRetentionPolicyRequest
        /// </summary>
        [Fact]
        public void CreateRetentionPolicyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateRetentionPolicyRequest
            //Assert.IsInstanceOfType<CreateRetentionPolicyRequest> (instance, "variable 'instance' is a CreateRetentionPolicyRequest");
        }


        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }

    }

}
