/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing FindEntityRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FindEntityRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FindEntityRequest
        //private FindEntityRequest instance;

        public FindEntityRequestTests()
        {
            // TODO uncomment below to create an instance of FindEntityRequest
            //instance = new FindEntityRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FindEntityRequest
        /// </summary>
        [Fact]
        public void FindEntityRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FindEntityRequest
            //Assert.IsInstanceOfType<FindEntityRequest> (instance, "variable 'instance' is a FindEntityRequest");
        }

        /// <summary>
        /// Test deserialize a FindClassificationsRequest from type FindEntityRequest
        /// </summary>
        [Fact]
        public void FindClassificationsRequestDeserializeFromFindEntityRequestTest()
        {
            // TODO uncomment below to test deserialize a FindClassificationsRequest from type FindEntityRequest
            //Assert.IsInstanceOf<FindEntityRequest>(JsonConvert.DeserializeObject<FindEntityRequest>(new FindClassificationsRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a FindRetentionPoliciesRequest from type FindEntityRequest
        /// </summary>
        [Fact]
        public void FindRetentionPoliciesRequestDeserializeFromFindEntityRequestTest()
        {
            // TODO uncomment below to test deserialize a FindRetentionPoliciesRequest from type FindEntityRequest
            //Assert.IsInstanceOf<FindEntityRequest>(JsonConvert.DeserializeObject<FindEntityRequest>(new FindRetentionPoliciesRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a FindGroupsRequest from type FindEntityRequest
        /// </summary>
        [Fact]
        public void FindGroupsRequestDeserializeFromFindEntityRequestTest()
        {
            // TODO uncomment below to test deserialize a FindGroupsRequest from type FindEntityRequest
            //Assert.IsInstanceOf<FindEntityRequest>(JsonConvert.DeserializeObject<FindEntityRequest>(new FindGroupsRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a FindCollectionsRequest from type FindEntityRequest
        /// </summary>
        [Fact]
        public void FindCollectionsRequestDeserializeFromFindEntityRequestTest()
        {
            // TODO uncomment below to test deserialize a FindCollectionsRequest from type FindEntityRequest
            //Assert.IsInstanceOf<FindEntityRequest>(JsonConvert.DeserializeObject<FindEntityRequest>(new FindCollectionsRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a FindUsersRequest from type FindEntityRequest
        /// </summary>
        [Fact]
        public void FindUsersRequestDeserializeFromFindEntityRequestTest()
        {
            // TODO uncomment below to test deserialize a FindUsersRequest from type FindEntityRequest
            //Assert.IsInstanceOf<FindEntityRequest>(JsonConvert.DeserializeObject<FindEntityRequest>(new FindUsersRequest().ToJson()));
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

    }

}
