/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing FindCollectionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FindCollectionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FindCollectionsRequest
        //private FindCollectionsRequest instance;

        public FindCollectionsRequestTests()
        {
            // TODO uncomment below to create an instance of FindCollectionsRequest
            //instance = new FindCollectionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FindCollectionsRequest
        /// </summary>
        [Fact]
        public void FindCollectionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FindCollectionsRequest
            //Assert.IsInstanceOfType<FindCollectionsRequest> (instance, "variable 'instance' is a FindCollectionsRequest");
        }



    }

}
