/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing FindGroupsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FindGroupsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FindGroupsRequest
        //private FindGroupsRequest instance;

        public FindGroupsRequestTests()
        {
            // TODO uncomment below to create an instance of FindGroupsRequest
            //instance = new FindGroupsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FindGroupsRequest
        /// </summary>
        [Fact]
        public void FindGroupsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FindGroupsRequest
            //Assert.IsInstanceOfType<FindGroupsRequest> (instance, "variable 'instance' is a FindGroupsRequest");
        }



    }

}
