/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing FindUsersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FindUsersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FindUsersRequest
        //private FindUsersRequest instance;

        public FindUsersRequestTests()
        {
            // TODO uncomment below to create an instance of FindUsersRequest
            //instance = new FindUsersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FindUsersRequest
        /// </summary>
        [Fact]
        public void FindUsersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FindUsersRequest
            //Assert.IsInstanceOfType<FindUsersRequest> (instance, "variable 'instance' is a FindUsersRequest");
        }



    }

}
