/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing UpdateRetentionPolicyRequestAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRetentionPolicyRequestAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRetentionPolicyRequestAllOf
        //private UpdateRetentionPolicyRequestAllOf instance;

        public UpdateRetentionPolicyRequestAllOfTests()
        {
            // TODO uncomment below to create an instance of UpdateRetentionPolicyRequestAllOf
            //instance = new UpdateRetentionPolicyRequestAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRetentionPolicyRequestAllOf
        /// </summary>
        [Fact]
        public void UpdateRetentionPolicyRequestAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateRetentionPolicyRequestAllOf
            //Assert.IsInstanceOfType<UpdateRetentionPolicyRequestAllOf> (instance, "variable 'instance' is a UpdateRetentionPolicyRequestAllOf");
        }


        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }

    }

}
