/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing UpdateCollectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCollectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCollectionRequest
        //private UpdateCollectionRequest instance;

        public UpdateCollectionRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateCollectionRequest
            //instance = new UpdateCollectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCollectionRequest
        /// </summary>
        [Fact]
        public void UpdateCollectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateCollectionRequest
            //Assert.IsInstanceOfType<UpdateCollectionRequest> (instance, "variable 'instance' is a UpdateCollectionRequest");
        }



    }

}
