/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HiarcSDK.Api;
using HiarcSDK.Model;
using HiarcSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing UserCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserCredentialsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserCredentials
        //private UserCredentials instance;

        public UserCredentialsTests()
        {
            // TODO uncomment below to create an instance of UserCredentials
            //instance = new UserCredentials();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserCredentials
        /// </summary>
        [Fact]
        public void UserCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserCredentials
            //Assert.IsInstanceOfType<UserCredentials> (instance, "variable 'instance' is a UserCredentials");
        }


        /// <summary>
        /// Test the property 'UserKey'
        /// </summary>
        [Fact]
        public void UserKeyTest()
        {
            // TODO unit test for the property 'UserKey'
        }
        /// <summary>
        /// Test the property 'BearerToken'
        /// </summary>
        [Fact]
        public void BearerTokenTest()
        {
            // TODO unit test for the property 'BearerToken'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

    }

}
