/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HiarcSDK.Client.OpenAPIDateConverter;

namespace HiarcSDK.Model
{
    /// <summary>
    /// Defines AccessLevel
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum AccessLevel
    {
        /// <summary>
        /// Enum CO_OWNER for value: CO_OWNER
        /// </summary>
        [EnumMember(Value = "CO_OWNER")]
        CO_OWNER = 1,

        /// <summary>
        /// Enum READ_WRITE for value: READ_WRITE
        /// </summary>
        [EnumMember(Value = "READ_WRITE")]
        READ_WRITE = 2,

        /// <summary>
        /// Enum READ_ONLY for value: READ_ONLY
        /// </summary>
        [EnumMember(Value = "READ_ONLY")]
        READ_ONLY = 3,

        /// <summary>
        /// Enum UPLOAD_ONLY for value: UPLOAD_ONLY
        /// </summary>
        [EnumMember(Value = "UPLOAD_ONLY")]
        UPLOAD_ONLY = 4

    }

}
