/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HiarcSDK.Client.OpenAPIDateConverter;

namespace HiarcSDK.Model
{
    /// <summary>
    /// AddFileToCollectionRequest
    /// </summary>
    [DataContract]
    public partial class AddFileToCollectionRequest :  IEquatable<AddFileToCollectionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddFileToCollectionRequest" /> class.
        /// </summary>
        /// <param name="fileKey">fileKey.</param>
        public AddFileToCollectionRequest(string fileKey = default(string))
        {
            this.FileKey = fileKey;
        }
        
        /// <summary>
        /// Gets or Sets FileKey
        /// </summary>
        [DataMember(Name="fileKey", EmitDefaultValue=false)]
        public string FileKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddFileToCollectionRequest {\n");
            sb.Append("  FileKey: ").Append(FileKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddFileToCollectionRequest);
        }

        /// <summary>
        /// Returns true if AddFileToCollectionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AddFileToCollectionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddFileToCollectionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FileKey == input.FileKey ||
                    (this.FileKey != null &&
                    this.FileKey.Equals(input.FileKey))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FileKey != null)
                    hashCode = hashCode * 59 + this.FileKey.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
