/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HiarcSDK.Client.OpenAPIDateConverter;

namespace HiarcSDK.Model
{
    /// <summary>
    /// AddUserToFileRequest
    /// </summary>
    [DataContract]
    public partial class AddUserToFileRequest :  IEquatable<AddUserToFileRequest>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets AccessLevel
        /// </summary>
        [DataMember(Name="accessLevel", EmitDefaultValue=false)]
        public AccessLevel? AccessLevel { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUserToFileRequest" /> class.
        /// </summary>
        /// <param name="userKey">userKey.</param>
        /// <param name="accessLevel">accessLevel.</param>
        public AddUserToFileRequest(string userKey = default(string), AccessLevel? accessLevel = default(AccessLevel?))
        {
            this.UserKey = userKey;
            this.AccessLevel = accessLevel;
        }
        
        /// <summary>
        /// Gets or Sets UserKey
        /// </summary>
        [DataMember(Name="userKey", EmitDefaultValue=false)]
        public string UserKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddUserToFileRequest {\n");
            sb.Append("  UserKey: ").Append(UserKey).Append("\n");
            sb.Append("  AccessLevel: ").Append(AccessLevel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddUserToFileRequest);
        }

        /// <summary>
        /// Returns true if AddUserToFileRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AddUserToFileRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddUserToFileRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserKey == input.UserKey ||
                    (this.UserKey != null &&
                    this.UserKey.Equals(input.UserKey))
                ) && 
                (
                    this.AccessLevel == input.AccessLevel ||
                    this.AccessLevel.Equals(input.AccessLevel)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserKey != null)
                    hashCode = hashCode * 59 + this.UserKey.GetHashCode();
                hashCode = hashCode * 59 + this.AccessLevel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
