/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HiarcSDK.Client.OpenAPIDateConverter;

namespace HiarcSDK.Model
{
    /// <summary>
    /// CreateFileRequestAllOf
    /// </summary>
    [DataContract]
    public partial class CreateFileRequestAllOf :  IEquatable<CreateFileRequestAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFileRequestAllOf" /> class.
        /// </summary>
        /// <param name="storageService">storageService.</param>
        public CreateFileRequestAllOf(string storageService = default(string))
        {
            this.StorageService = storageService;
        }
        
        /// <summary>
        /// Gets or Sets StorageService
        /// </summary>
        [DataMember(Name="storageService", EmitDefaultValue=false)]
        public string StorageService { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateFileRequestAllOf {\n");
            sb.Append("  StorageService: ").Append(StorageService).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateFileRequestAllOf);
        }

        /// <summary>
        /// Returns true if CreateFileRequestAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateFileRequestAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateFileRequestAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StorageService == input.StorageService ||
                    (this.StorageService != null &&
                    this.StorageService.Equals(input.StorageService))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StorageService != null)
                    hashCode = hashCode * 59 + this.StorageService.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
