/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HiarcSDK.Client.OpenAPIDateConverter;

namespace HiarcSDK.Model
{
    /// <summary>
    /// FileDirectUpload
    /// </summary>
    [DataContract]
    public partial class FileDirectUpload :  IEquatable<FileDirectUpload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileDirectUpload" /> class.
        /// </summary>
        /// <param name="directUploadUrl">directUploadUrl.</param>
        /// <param name="storageId">storageId.</param>
        /// <param name="storageService">storageService.</param>
        /// <param name="expiresAt">expiresAt.</param>
        public FileDirectUpload(string directUploadUrl = default(string), string storageId = default(string), string storageService = default(string), DateTime expiresAt = default(DateTime))
        {
            this.DirectUploadUrl = directUploadUrl;
            this.StorageId = storageId;
            this.StorageService = storageService;
            this.ExpiresAt = expiresAt;
        }
        
        /// <summary>
        /// Gets or Sets DirectUploadUrl
        /// </summary>
        [DataMember(Name="directUploadUrl", EmitDefaultValue=false)]
        public string DirectUploadUrl { get; set; }

        /// <summary>
        /// Gets or Sets StorageId
        /// </summary>
        [DataMember(Name="storageId", EmitDefaultValue=false)]
        public string StorageId { get; set; }

        /// <summary>
        /// Gets or Sets StorageService
        /// </summary>
        [DataMember(Name="storageService", EmitDefaultValue=false)]
        public string StorageService { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name="expiresAt", EmitDefaultValue=false)]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileDirectUpload {\n");
            sb.Append("  DirectUploadUrl: ").Append(DirectUploadUrl).Append("\n");
            sb.Append("  StorageId: ").Append(StorageId).Append("\n");
            sb.Append("  StorageService: ").Append(StorageService).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FileDirectUpload);
        }

        /// <summary>
        /// Returns true if FileDirectUpload instances are equal
        /// </summary>
        /// <param name="input">Instance of FileDirectUpload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileDirectUpload input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DirectUploadUrl == input.DirectUploadUrl ||
                    (this.DirectUploadUrl != null &&
                    this.DirectUploadUrl.Equals(input.DirectUploadUrl))
                ) && 
                (
                    this.StorageId == input.StorageId ||
                    (this.StorageId != null &&
                    this.StorageId.Equals(input.StorageId))
                ) && 
                (
                    this.StorageService == input.StorageService ||
                    (this.StorageService != null &&
                    this.StorageService.Equals(input.StorageService))
                ) && 
                (
                    this.ExpiresAt == input.ExpiresAt ||
                    (this.ExpiresAt != null &&
                    this.ExpiresAt.Equals(input.ExpiresAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DirectUploadUrl != null)
                    hashCode = hashCode * 59 + this.DirectUploadUrl.GetHashCode();
                if (this.StorageId != null)
                    hashCode = hashCode * 59 + this.StorageId.GetHashCode();
                if (this.StorageService != null)
                    hashCode = hashCode * 59 + this.StorageService.GetHashCode();
                if (this.ExpiresAt != null)
                    hashCode = hashCode * 59 + this.ExpiresAt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
