/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using HiarcSDK.Client;
using HiarcSDK.Api;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing AdminApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdminApiTests : IDisposable
    {
        private AdminApi instance;

        public AdminApiTests()
        {
            instance = new AdminApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AdminApi
            //Assert.IsType(typeof(AdminApi), instance, "instance is a AdminApi");
        }

        
        /// <summary>
        /// Test InitDB
        /// </summary>
        [Fact]
        public void InitDBTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InitDB();
            //Assert.IsType<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ResetDB
        /// </summary>
        [Fact]
        public void ResetDBTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ResetDB();
            //Assert.IsType<Object> (response, "response is Object");
        }
        
    }

}
