/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using HiarcSDK.Client;
using HiarcSDK.Api;
using HiarcSDK.Model;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing FilesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FilesApiTests : IDisposable
    {
        private FilesApi instance;

        public FilesApiTests()
        {
            instance = new FilesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FilesApi
            //Assert.IsType(typeof(FilesApi), instance, "instance is a FilesApi");
        }

        
        /// <summary>
        /// Test FilterAllowedFiles
        /// </summary>
        [Fact]
        public void FilterAllowedFilesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AllowedFilesRequest allowedFilesRequest = null;
            //string xHiarcUserKey = null;
            //var response = instance.FilterAllowedFiles(allowedFilesRequest, xHiarcUserKey);
            //Assert.IsType<List<string>> (response, "response is List<string>");
        }
        
    }

}
