/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using HiarcSDK.Client;
using HiarcSDK.Api;
using HiarcSDK.Model;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing RetentionPolicyApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RetentionPolicyApiTests : IDisposable
    {
        private RetentionPolicyApi instance;

        public RetentionPolicyApiTests()
        {
            instance = new RetentionPolicyApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RetentionPolicyApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RetentionPolicyApi
            //Assert.IsType(typeof(RetentionPolicyApi), instance, "instance is a RetentionPolicyApi");
        }

        
        /// <summary>
        /// Test CreateRetentionPolicy
        /// </summary>
        [Fact]
        public void CreateRetentionPolicyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateRetentionPolicyRequest createRetentionPolicyRequest = null;
            //var response = instance.CreateRetentionPolicy(createRetentionPolicyRequest);
            //Assert.IsType<RetentionPolicy> (response, "response is RetentionPolicy");
        }
        
        /// <summary>
        /// Test FindRetentionPolicies
        /// </summary>
        [Fact]
        public void FindRetentionPoliciesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FindRetentionPoliciesRequest findRetentionPoliciesRequest = null;
            //var response = instance.FindRetentionPolicies(findRetentionPoliciesRequest);
            //Assert.IsType<List<RetentionPolicy>> (response, "response is List<RetentionPolicy>");
        }
        
        /// <summary>
        /// Test GetAllRetentionPolicies
        /// </summary>
        [Fact]
        public void GetAllRetentionPoliciesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllRetentionPolicies();
            //Assert.IsType<List<RetentionPolicy>> (response, "response is List<RetentionPolicy>");
        }
        
        /// <summary>
        /// Test GetRetentionPolicy
        /// </summary>
        [Fact]
        public void GetRetentionPolicyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string key = null;
            //var response = instance.GetRetentionPolicy(key);
            //Assert.IsType<RetentionPolicy> (response, "response is RetentionPolicy");
        }
        
        /// <summary>
        /// Test UpdateRetentionPolicy
        /// </summary>
        [Fact]
        public void UpdateRetentionPolicyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string key = null;
            //UpdateRetentionPolicyRequest updateRetentionPolicyRequest = null;
            //var response = instance.UpdateRetentionPolicy(key, updateRetentionPolicyRequest);
            //Assert.IsType<RetentionPolicy> (response, "response is RetentionPolicy");
        }
        
    }

}
