/* 
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using HiarcSDK.Client;
using HiarcSDK.Api;
using HiarcSDK.Model;

namespace HiarcSDK.Test
{
    /// <summary>
    ///  Class for testing TokenApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TokenApiTests : IDisposable
    {
        private TokenApi instance;

        public TokenApiTests()
        {
            instance = new TokenApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TokenApi
            //Assert.IsType(typeof(TokenApi), instance, "instance is a TokenApi");
        }

        
        /// <summary>
        /// Test CreateUserToken
        /// </summary>
        [Fact]
        public void CreateUserTokenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateUserTokenRequest createUserTokenRequest = null;
            //var response = instance.CreateUserToken(createUserTokenRequest);
            //Assert.IsType<UserCredentials> (response, "response is UserCredentials");
        }
        
    }

}
